modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/UltimatePokeBuilder/issues"
showAsResourcePack=false

[[mods]]
  modId="ultimatepokebuilder"
  version="2.2.1"
  displayName="UltimatePokeBuilder"
  displayURL="https://discord.gg/7vqgtrjDGw"
  credits="Envyful"
  authors="Envyful"
  description='''
  UPB
  '''

  [[dependencies.ultimatepokebuilder]]
  modId="forge"
  mandatory=true
  versionRange="[47.1.28,)"
  ordering="NONE"
  side="BOTH"

  [[dependencies.ultimatepokebuilder]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1,1.21)"
  ordering="NONE"
  side="BOTH"